version: '3.9'
services:
  api:
    build: .
    command: gunicorn stock_prediction_main.wsgi:application --bind 0.0.0.0:8000 --workers 3
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    healthcheck:
      test: ["CMD", "curl", "-fs", "http://localhost:8000/healthz/"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on: [] 